(()=>{
"use strict";

// v9.4: permanently remove stale Nanako service workers/caches during Omni stabilization.
(async()=>{
  try{
    if("serviceWorker" in navigator){
      const regs=await navigator.serviceWorker.getRegistrations();
      for(const reg of regs) await reg.unregister();
    }
    if("caches" in window){
      const keys=await caches.keys();
      for(const key of keys) await caches.delete(key);
    }
    try{
      localStorage.removeItem("nanakoVoiceOutput");
      localStorage.removeItem("nanako_voice_output");
      localStorage.removeItem("voiceOutput");
      localStorage.removeItem("voice_output");
    }catch{}
    console.log("[Nanako v9.4] stale service workers/caches/voice-output state purged");
  }catch(err){ console.warn("[Nanako v9.4] purge warning",err); }
})();
console.log("[Nanako Frontend] v9.3 AUDIO ALWAYS ON");
// v9.1 SAFETY: purge legacy service workers/caches from pre-Omni frontend builds.
// The app intentionally runs without a service worker during Omni stabilization.
(async()=>{
  try{
    if("serviceWorker" in navigator){
      const regs=await navigator.serviceWorker.getRegistrations();
      await Promise.all(regs.map(r=>r.unregister()));
    }
    if("caches" in window){
      const keys=await caches.keys();
      await Promise.all(keys.map(k=>caches.delete(k)));
    }
    console.log("[Nanako v9.1] Legacy service workers/caches purged. Inline Omni audio frontend active.");
  }catch(err){console.warn("[Nanako v9.1] Cache purge warning:",err);}
})();



// ============================================================
// NANAKO v11 STEP 1.2 — THIN ANIMATION RENDERER
//
// IMPORTANT:
// Python on Alibaba decides blink timing, mouth timing, emotion,
// idle/talking state and breathing values.
// This browser code ONLY displays the animation protocol it receives.
// ============================================================
const ANIMATION_ASSETS = {
  neutral: {
    base: "./static/characters/nanako/states/neutral/base.png",
    eyes: {
      open: "./static/characters/nanako/states/neutral/eyes/open.png",
      half: "./static/characters/nanako/states/neutral/eyes/half.png",
      closed: "./static/characters/nanako/states/neutral/eyes/closed.png"
    },
    mouth: {
      closed: "./static/characters/nanako/states/neutral/mouth/closed.png",
      small: "./static/characters/nanako/states/neutral/mouth/small.png",
      medium: "./static/characters/nanako/states/neutral/mouth/medium.png",
      wide: "./static/characters/nanako/states/neutral/mouth/wide.png",
      round: "./static/characters/nanako/states/neutral/mouth/round.png"
    }
  },
  confused: {
    base: "./static/characters/nanako/states/confused/base.png",
    eyes: {
      open: "./static/characters/nanako/states/confused/eyes/open.png",
      half: "./static/characters/nanako/states/confused/eyes/half.png",
      closed: "./static/characters/nanako/states/confused/eyes/closed.png"
    },
    mouth: {
      closed: "./static/characters/nanako/states/confused/mouth/closed.png",
      small: "./static/characters/nanako/states/confused/mouth/small.png",
      medium: "./static/characters/nanako/states/confused/mouth/medium.png",
      wide: "./static/characters/nanako/states/confused/mouth/wide.png",
      round: "./static/characters/nanako/states/confused/mouth/round.png"
    }
  }
};

let nanakoBase=null,nanakoEyes=null,nanakoMouth=null,nanakoMotion=null,nanakoAvatar=null;
let animationRaf=0;
let animationToken=0;
let idlePlanTimer=0;
let currentAnimationPlan=null;

function animationAsset(state, part, frame){
  const emotion=ANIMATION_ASSETS[state]?state:"neutral";
  if(part==="base")return ANIMATION_ASSETS[emotion].base;
  const table=ANIMATION_ASSETS[emotion][part]||ANIMATION_ASSETS.neutral[part];
  return table[frame]||table.open||table.closed;
}

function renderAnimationFrame(frame){
  if(!frame)return;
  const emotion=ANIMATION_ASSETS[frame.emotion]?frame.emotion:"neutral";
  const base=animationAsset(emotion,"base");
  const eyes=animationAsset(emotion,"eyes",frame.eyes||"open");
  const mouth=animationAsset(emotion,"mouth",frame.mouth||"closed");
  if(nanakoBase&&nanakoBase.getAttribute("src")!==base)nanakoBase.src=base;
  if(nanakoEyes&&nanakoEyes.getAttribute("src")!==eyes)nanakoEyes.src=eyes;
  if(nanakoMouth&&nanakoMouth.getAttribute("src")!==mouth)nanakoMouth.src=mouth;

  // These transform NUMBERS are generated by Python.
  // JS only applies them to the display surface.
  const scale=Number.isFinite(Number(frame.scale))?Number(frame.scale):1;
  const y=Number.isFinite(Number(frame.translate_y))?Number(frame.translate_y):0;
  if(nanakoMotion)nanakoMotion.style.transform=`translateY(${y}px) scale(${scale})`;

  if(nanakoAvatar){
    nanakoAvatar.dataset.emotion=emotion;
    nanakoAvatar.dataset.action=frame.action||"idle";
  }
}

function stopAnimationPlan(){
  animationToken+=1;
  if(animationRaf)cancelAnimationFrame(animationRaf);
  animationRaf=0;
  currentAnimationPlan=null;
}

function playAnimationPlan(plan,{loop=false,onComplete=null}={}){
  stopAnimationPlan();
  if(!plan||!Array.isArray(plan.frames)||!plan.frames.length)return;
  const token=animationToken;
  currentAnimationPlan=plan;
  const started=performance.now();
  const duration=Math.max(1,Number(plan.duration_ms)||1);

  const tick=now=>{
    if(token!==animationToken)return;
    let elapsed=now-started;
    if(loop)elapsed=elapsed%duration;
    let frames=plan.frames;
    let lo=0,hi=frames.length-1;
    while(lo<hi){
      const mid=Math.ceil((lo+hi)/2);
      if((Number(frames[mid].t)||0)<=elapsed)lo=mid;
      else hi=mid-1;
    }
    renderAnimationFrame(frames[lo]);
    if(loop||elapsed<duration){
      animationRaf=requestAnimationFrame(tick);
    }else{
      animationRaf=0;
      if(typeof onComplete==="function")onComplete();
    }
  };
  animationRaf=requestAnimationFrame(tick);
}

async function requestIdleAnimation(){
  clearTimeout(idlePlanTimer);
  if(currentAudio)return;
  try{
    const r=await fetch(`${API}/api/animation/idle-plan?duration_ms=60000&sample_ms=100`,{cache:"no-store"});
    const d=await r.json();
    if(!r.ok||!d?.ok||!d?.animation_plan)throw new Error(d?.error||`Animation request failed (${r.status})`);
    if(!currentAudio){
      playAnimationPlan(d.animation_plan,{loop:false,onComplete:()=>requestIdleAnimation()});
    }
  }catch(err){
    console.warn("[Nanako Animation] Python idle plan unavailable:",err);
    renderAnimationFrame({emotion:"neutral",action:"idle",eyes:"open",mouth:"closed",scale:1,translate_y:0});
    idlePlanTimer=setTimeout(requestIdleAnimation,5000);
  }
}

function useTalkingAnimation(plan){
  clearTimeout(idlePlanTimer);
  if(plan?.frames?.length)playAnimationPlan(plan);
  else renderAnimationFrame({emotion:"neutral",action:"talking",eyes:"open",mouth:"small",scale:1,translate_y:0});
}

function returnToPythonIdle(){
  stopAnimationPlan();
  requestIdleAnimation();
}


// ============================================================
// APP / VOICE LOGIC
// ============================================================
console.log("[Nanako Build] v9.4 FORCE AUDIO ON / NO VOICE OUTPUT TOGGLE");
const API="https://nanako-web-pokbkohedy.ap-southeast-1.fcapp.run",CHAT=`${API}/api/chat`,VOICE=`${API}/api/voice`,RESET=`${API}/api/reset`;
const RUNTIME_CHECK=`${API}/runtime-check`;
async function checkPythonRuntime(){const el=document.getElementById("runtimeStatus");try{const r=await fetch(RUNTIME_CHECK,{cache:"no-store"});const d=await r.json();const ok=!!(d.python_running&&d.mic_engine_loaded&&d.animation_engine_loaded&&d.qwen_backend_configured);if(el)el.textContent=ok?"Python runtime: ONLINE • mic + animation loaded":"Python runtime: incomplete — check Alibaba deployment";console.log("[Nanako v11 runtime-check]",d);}catch(err){if(el)el.textContent="Python runtime: OFFLINE / unreachable";console.warn("[Nanako v11 runtime-check failed]",err);}}
setTimeout(checkPythonRuntime,150);
const VAD={
  calibrationMs:350,
  minSpeechMs:220,
  silenceToEndMs:1500,
  noSpeechRestartMs:12000,
  maxTurnMs:30000,
  startFloor:.007,
  continueFloor:.0045,
  startNoiseMultiplier:1.5,
  continueNoiseMultiplier:1.15
};
const $=id=>document.getElementById(id),e={levelBadge:$("levelBadge"),scoreFill:$("scoreFill"),scoreText:$("scoreText"),settingsScore:$("settingsScore"),settingsScoreFill:$("settingsScoreFill"),userTranscript:$("userTranscript"),userTranscriptText:$("userTranscriptText"),status:$("statusText"),ro:$("romajiButton"),en:$("englishButton"),mute:$("muteButton"),jp:$("japaneseReply"),roSec:$("romajiSection"),enSec:$("englishSection"),roText:$("romajiReply"),enText:$("englishReply"),input:$("messageInput"),send:$("sendButton"),conv:$("conversationButton"),corr:$("correctionToast"),wrong:$("wrongText"),correct:$("correctText"),err:$("errorToast"),settings:$("settingsModal"),menu:$("menuButton"),closeSettings:$("closeSettingsButton"),historyBtn:$("historyButton"),historyModal:$("historyModal"),closeHistory:$("closeHistoryButton"),historyEmpty:$("historyEmpty"),historyList:$("historyList"),levelValue:$("levelValue"),levelGrid:$("levelGrid"),reset:$("resetButton"),debugMic:$("debugMic"),debugRoom:$("debugRoom"),debugSpeech:$("debugSpeech"),debugTurn:$("debugTurn")};
let level="auto",score=0,showRO=false,showEN=false,muted=false,active=false,busy=false,currentAudio=null,currentAudioObjectUrl="",stream=null,rec=null,chunks=[],ctx=null,analyser=null,data=null,raf=0,noiseSamples=[],noiseFloor=.003,lastGoodNoiseFloor=.003,hasGoodNoiseFloor=false,speech=false,candidate=0,firstSpeech=0,lastSpeech=0,turnStart=0,transcriptTimer=0,correctionTimer=0,uploadThisRecording=false,audioUnlocked=false;const history=[];const ttsAudio=new Audio();ttsAudio.preload="auto";ttsAudio.playsInline=true;
const SILENT_WAV="data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA=";
const status=t=>e.status.textContent=t,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),label=l=>l==="auto"?"Auto":l.toUpperCase();
function setScore(v){score=clamp(Math.round(Number(v)||0),0,100);let w=`${score}%`;e.scoreText.textContent=score;e.scoreFill.style.width=w;e.settingsScore.textContent=`${score} / 100`;e.settingsScoreFill.style.width=w}
function error(m){e.err.textContent=String(m||"Something went wrong.");e.err.hidden=false;clearTimeout(error.t);error.t=setTimeout(()=>e.err.hidden=true,6000)}
function transcript(t){clearTimeout(transcriptTimer);if(!t){e.userTranscript.hidden=true;return}e.userTranscriptText.textContent=t;e.userTranscript.style.opacity="1";e.userTranscript.hidden=false;transcriptTimer=setTimeout(()=>{e.userTranscript.style.opacity="0";setTimeout(()=>e.userTranscript.hidden=true,420)},2200)}
function correction(d){let a=d?.analysis&&typeof d.analysis==="object"?d.analysis:{},o=String(a.wrong_text??a.original??a.original_text??a.user_text??"").trim(),c=String(a.correct_text??a.corrected??a.corrected_text??a.correction??"").trim(),n=a.needs_correction===true||a.correct===false||a.is_correct===false||!!(o&&c&&o!==c);return{n,o,c}}
function showCorrection(x){clearTimeout(correctionTimer);if(!x.n||!x.o||!x.c){e.corr.hidden=true;return}e.wrong.textContent=x.o;e.correct.textContent=`→ ${x.c}`;e.corr.hidden=false;correctionTimer=setTimeout(()=>e.corr.hidden=true,7000)}
function addHistory(role,text,x=null){history.push({role,text:String(text||""),wrong:x?.n?x.o:"",corrected:x?.n?x.c:""});renderHistory()}
function renderHistory(){e.historyList.innerHTML="";e.historyEmpty.hidden=history.length>0;history.forEach(h=>{let b=document.createElement("div");b.className=`history-bubble ${h.role==="user"?"user":""}`;let r=document.createElement("div");r.className="history-role";r.textContent=h.role==="user"?"YOU":"NANAKO";let t=document.createElement("div");t.className="history-text";t.textContent=h.text;b.append(r,t);if(h.wrong&&h.corrected){let c=document.createElement("div");c.className="history-correction";c.innerHTML=`<div class="history-wrong"></div><div class="history-correct"></div>`;c.children[0].textContent=h.wrong;c.children[1].textContent=h.corrected;b.append(c)}e.historyList.append(b)})}
function quick(){e.ro.classList.toggle("active",showRO);e.roSec.hidden=!showRO;e.en.classList.toggle("active",showEN);e.enSec.hidden=!showEN;e.mute.classList.toggle("active",muted);e.mute.textContent=muted?"🔇":"🔊"}
function convButton(){e.conv.classList.toggle("active",active);if(currentAudio&&active){e.conv.classList.add("interrupt");e.conv.textContent="✋ Interrupt Nanako"}else{e.conv.classList.remove("interrupt");e.conv.textContent=active?"⏹ End Conversation":"🎤 Start Conversation"}}
async function jsonResp(r){let d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d?.error||d?.message||`Request failed (${r.status})`);return d}
async function apply(d,user){e.jp.textContent=String(d?.reply||"");e.roText.textContent=String(d?.romaji||"");e.enText.textContent=String(d?.english||"");let s=Number(d?.conversation_score??d?.score??d?.analysis?.conversation_score);if(Number.isFinite(s))setScore(s);let x=correction(d);showCorrection(x);addHistory("user",user,x);addHistory("assistant",d?.reply||"");let b=d?.audio_base64||d?.tts_audio_base64||d?.audio||"",m=d?.audio_mime||d?.mime_type||"audio/wav";if(b&&!muted)await play(b,m,d?.animation_plan);else{if(d?.animation_plan)playAnimationPlan(d.animation_plan);if(active)setTimeout(begin,20)}}
async function send(){let t=e.input.value.trim();if(!t||busy)return;busy=true;status("Nanako is thinking...");try{let r=await fetch(CHAT,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t,level,voice_output:true})}),d=await jsonResp(r);e.input.value="";transcript(t);await apply(d,t)}catch(x){console.error(x);error(x.message);status("Chat failed.")}finally{busy=false;if(!currentAudio&&!active)status("Ready to chat")}}
function normalizeAudioSource(b,m){let v=String(b||"");if(!v)return"";if(v.startsWith("data:"))return v;return`data:${m||"audio/wav"};base64,${v}`}
function audioBlobUrlFromBase64(b,m){let v=String(b||"").trim();if(!v)return"";if(v.startsWith("data:"))v=v.slice(v.indexOf(",")+1);const bin=atob(v);const bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return URL.createObjectURL(new Blob([bytes],{type:m||"audio/wav"}))}
function revokeCurrentAudioObjectUrl(){if(currentAudioObjectUrl){try{URL.revokeObjectURL(currentAudioObjectUrl)}catch{}currentAudioObjectUrl=""}}
function unlockAudio(){
  if(audioUnlocked) return;
  try{
    // iOS Safari cold-start unlock. IMPORTANT: do not await, pause, or reset
    // this element. Starting playback inside the user's tap is enough to
    // grant media playback permission; the tiny silent WAV then ends by itself.
    // The same ttsAudio element is later reused for Nanako's real voice.
    ttsAudio.src=SILENT_WAV;
    ttsAudio.volume=.01;
    ttsAudio.preload="auto";
    const p=ttsAudio.play();
    if(p&&typeof p.then==="function")p.then(()=>{
      audioUnlocked=true;
      console.log("[Nanako Audio] iOS playback primed on first tap.");
    }).catch(x=>console.warn("[Nanako Audio] unlock attempt failed:",x));
    // Restore normal volume after the silent clip has had time to finish.
    setTimeout(()=>{if(!currentAudio)ttsAudio.volume=1;},180);
  }catch(x){
    console.warn("[Nanako Audio] unlock attempt failed:",x);
  }
}

async function stopAudio(resume=false){
  if(currentAudio){
    try{
      currentAudio.onplaying=null;
      currentAudio.onended=null;
      currentAudio.onerror=null;
      currentAudio.pause();
      currentAudio.src="";
      currentAudio.load();
      revokeCurrentAudioObjectUrl();
    }catch{}
    currentAudio=null;
  }
  stopAnimationPlan();
  convButton();
  if(resume&&active){
    status("Listening...");
    setTimeout(begin,40);
  }
}

async function play(b,m,animationPlan=null){
  if(!b||muted){
    if(active)setTimeout(begin,40);
    return false;
  }

  await stopAudio(false);

  // Safari simplification:
  // completely release microphone capture while Nanako is speaking.
  // Interruption is manual via the on-screen button.
  cleanup();
  release();


  const a=ttsAudio;
  revokeCurrentAudioObjectUrl();
  try{currentAudioObjectUrl=audioBlobUrlFromBase64(b,m);a.src=currentAudioObjectUrl;}catch(blobErr){console.warn("[Nanako Audio] Blob conversion failed; using data URL.",blobErr);a.src=normalizeAudioSource(b,m);}
  a.preload="auto";
  a.volume=1;
  a.playbackRate=.86;
  a.defaultPlaybackRate=.86;
  currentAudio=a;


  convButton();

  let finished=false;
  const finish=()=>{
    if(finished)return;
    finished=true;
    returnToPythonIdle();
    if(currentAudio===a)currentAudio=null;
    convButton();
    if(active){
      status("Listening...");
      // Reacquire mic only AFTER TTS is completely finished or interrupted.
      setTimeout(begin,50);
    }else{
      status("Ready to chat");
    }
  };

  a.onplaying=()=>{
    if(currentAudio!==a)return;
    useTalkingAnimation(animationPlan);
    status("Nanako is speaking...");
    convButton();
    console.log("[Nanako Audio] Playback started. Mic is OFF during TTS.");
  };
  a.onended=()=>{
    console.log("[Nanako Audio] Finished speaking.");
    finish();
  };
  a.onerror=()=>{
    console.error("[Nanako Audio] Playback error.");
    finish();
  };

  try{
    await a.play();
    if(currentAudio===a)useTalkingAnimation(animationPlan);
    return true;
  }catch(x){
    console.error("[Nanako TTS] Playback failed:",x);
    error("Nanako's voice could not play. Tap Start Conversation once more to unlock audio.");
    finish();
    return false;
  }
}

async function mic(){if(stream&&stream.getTracks().some(t=>t.readyState==="live"))return stream;if(!navigator.mediaDevices?.getUserMedia)throw new Error("Microphone access requires HTTPS.");stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1}});return stream}
function release(){stream?.getTracks().forEach(t=>t.stop());stream=null}
function mime(){let c=["audio/mp4","audio/webm;codecs=opus","audio/webm","audio/ogg;codecs=opus"];return c.find(t=>MediaRecorder.isTypeSupported?.(t))||""}
function rms(a){let s=0;for(let v of a)s+=v*v;return Math.sqrt(s/a.length)}
function cleanup(){if(raf)cancelAnimationFrame(raf);raf=0;try{ctx?.close()}catch{}ctx=analyser=data=null}
function monitor(){if(!active||!rec||rec.state!=="recording"||!analyser||!data)return;analyser.getFloatTimeDomainData(data);let r=rms(data),now=performance.now(),age=now-turnStart;let db=r>0?20*Math.log10(r):-120,room=noiseFloor>0?20*Math.log10(noiseFloor):-120;e.debugMic.textContent=`Mic: ${db.toFixed(1)} dB`;e.debugRoom.textContent=`Room: ${room.toFixed(1)} dB`;e.debugSpeech.textContent=`Speech: ${speech?"Detected":"Waiting"}`;e.debugTurn.textContent=`Turn: ${(age/1000).toFixed(1)} sec`;
if(!hasGoodNoiseFloor&&age<VAD.calibrationMs){noiseSamples.push(r);if(noiseSamples.length){let sorted=[...noiseSamples].sort((a,b)=>a-b);noiseFloor=sorted[Math.floor(sorted.length*.5)]||noiseFloor}raf=requestAnimationFrame(monitor);return}
if(!hasGoodNoiseFloor){if(noiseSamples.length){let sorted=[...noiseSamples].sort((a,b)=>a-b);noiseFloor=sorted[Math.floor(sorted.length*.5)]||noiseFloor}lastGoodNoiseFloor=noiseFloor;hasGoodNoiseFloor=true;console.log("[Nanako Web VAD] Room calibration saved:",noiseFloor.toFixed(5))}else{noiseFloor=lastGoodNoiseFloor}
let st=Math.max(VAD.startFloor,noiseFloor*VAD.startNoiseMultiplier),ct=Math.max(VAD.continueFloor,noiseFloor*VAD.continueNoiseMultiplier);
if(!speech){if(r>=st){if(!candidate)candidate=now;if(now-candidate>=VAD.minSpeechMs){speech=true;firstSpeech=now;lastSpeech=now;status("I'm listening...");console.log("[Nanako Web VAD] Speech started.")}}else{candidate=0}if(age>=VAD.noSpeechRestartMs){console.log("[Nanako Web VAD] No speech timeout.");stopRec(false);return}}else{if(r>=ct)lastSpeech=now;if(now-firstSpeech>=VAD.minSpeechMs&&now-lastSpeech>=VAD.silenceToEndMs){console.log("[Nanako Web VAD] End of speech:",Math.round(now-lastSpeech),"ms silence");stopRec(true);return}}
if(age>=VAD.maxTurnMs){stopRec(speech);return}raf=requestAnimationFrame(monitor)}
async function startRec(){if(!active||busy||currentAudio||rec?.state==="recording")return;try{let s=await mic();if(!window.MediaRecorder)throw new Error("This browser does not support MediaRecorder.");cleanup();let AC=window.AudioContext||window.webkitAudioContext;if(AC){ctx=new AC();if(ctx.state==="suspended")await ctx.resume();let src=ctx.createMediaStreamSource(s);analyser=ctx.createAnalyser();analyser.fftSize=1024;data=new Float32Array(analyser.fftSize);src.connect(analyser)}chunks=[];noiseSamples=[];noiseFloor=hasGoodNoiseFloor?lastGoodNoiseFloor:.003;speech=false;candidate=0;firstSpeech=lastSpeech=0;uploadThisRecording=false;turnStart=performance.now();let mt=mime();rec=mt?new MediaRecorder(s,{mimeType:mt}):new MediaRecorder(s);let rr=rec;rr.ondataavailable=x=>{if(x.data?.size)chunks.push(x.data)};rr.onstop=async()=>{rec=null;cleanup();if(!uploadThisRecording||!chunks.length){chunks=[];if(active)setTimeout(begin,60);return}let type=rr.mimeType||chunks[0]?.type||"audio/mp4",b=new Blob(chunks,{type});chunks=[];await uploadVoice(b)};rr.start(160);status("Listening...");raf=requestAnimationFrame(monitor)}catch(x){console.error(x);error(x.message);status("Microphone unavailable");await stopMode()}}
function stopRec(upload=true){if(!rec)return;if(raf)cancelAnimationFrame(raf);raf=0;uploadThisRecording=upload;if(rec.state!=="inactive")rec.stop()}
async function uploadVoice(b){if(!active)return;busy=true;status("Nanako is thinking...");try{let f=new FormData(),type=b.type||"audio/mp4",ext=type.includes("mp4")?"m4a":type.includes("ogg")?"ogg":"webm";f.append("audio",b,`nanako_voice.${ext}`);f.append("level",level);const requestedVoiceOutput = true;
  f.append("voice_output", "true");
  console.log(`[Nanako Voice Request] voice_output=FORCED_TRUE muted=${muted}`);let r=await fetch(VOICE,{method:"POST",body:f}),d=await jsonResp(r);if(d?.ignored){if(active){status("Listening...");setTimeout(begin,60)}return}let t=String(d?.transcript||"");console.log("[Nanako Web Voice] Transcript:",t);transcript(t);await apply(d,t)}catch(x){console.error(x);error(x.message);status("Voice turn failed");if(active)setTimeout(begin,500)}finally{busy=false}}
async function begin(){if(!active||busy||currentAudio||rec?.state==="recording")return;await startRec()}
async function startMode(){
  if(active)return;
  try{
    // Both permission-sensitive actions are initiated by the SAME first tap.
    // Audio priming is fire-and-forget; it never blocks microphone startup.
    active=true;
    convButton();
    unlockAudio();
    status("Starting microphone...");
    await begin();
  }catch(x){
    console.error(x);
    error("Please allow microphone access in Safari.");
  }
}
async function stopMode(){active=false;if(rec?.state==="recording")stopRec(false);cleanup();release();await stopAudio(false);convButton();status("Ready to chat")}
async function reset(){await stopMode();try{await fetch(RESET,{method:"POST"})}catch{}history.length=0;renderHistory();setScore(0);e.jp.textContent="こんにちは！ななこです。今日も気楽に話そう。";e.roText.textContent=e.enText.textContent="";e.corr.hidden=e.settings.hidden=e.historyModal.hidden=true}

e.send.onclick=send;e.input.onkeydown=x=>{if(x.key==="Enter"){x.preventDefault();send()}};e.ro.onclick=()=>{showRO=!showRO;quick()};e.en.onclick=()=>{showEN=!showEN;quick()};e.mute.onclick=async()=>{muted=!muted;quick();if(muted&&currentAudio)await stopAudio(active)};e.conv.onclick=async()=>{if(currentAudio&&active){console.log("[Nanako] Manual interruption.");stopAudio(true);return}active?await stopMode():await startMode()};e.menu.onclick=()=>e.settings.hidden=false;e.closeSettings.onclick=()=>e.settings.hidden=true;e.historyBtn.onclick=()=>{e.settings.hidden=true;e.historyModal.hidden=false};e.closeHistory.onclick=()=>e.historyModal.hidden=true;e.settings.onclick=x=>{if(x.target===e.settings)e.settings.hidden=true};e.historyModal.onclick=x=>{if(x.target===e.historyModal)e.historyModal.hidden=true};e.levelGrid.onclick=x=>{let b=x.target.closest("[data-level]");if(!b)return;level=b.dataset.level;e.levelGrid.querySelectorAll("[data-level]").forEach(c=>c.classList.toggle("active",c.dataset.level===level));e.levelBadge.textContent=e.levelValue.textContent=label(level)};e.reset.onclick=reset;
window.addEventListener("beforeunload",()=>{
  stopAnimationPlan();
  active=false;
  try{if(rec?.state==="recording")rec.stop()}catch{}
  cleanup();
  release();
  currentAudio?.pause();
});

document.addEventListener("visibilitychange",()=>{
  if(document.visibilityState==="visible"&&!currentAudio)requestIdleAnimation();
});


async function boot(){
  setScore(0);quick();convButton();renderHistory();
  nanakoAvatar=document.getElementById("nanakoAvatar");
  nanakoBase=document.getElementById("nanakoBase");
  nanakoEyes=document.getElementById("nanakoEyes");
  nanakoMouth=document.getElementById("nanakoMouth");
  nanakoMotion=document.querySelector(".nanako-motion");
  renderAnimationFrame({emotion:"neutral",action:"idle",eyes:"open",mouth:"closed",scale:1,translate_y:0});
  if(nanakoAvatar)nanakoAvatar.classList.add("face-ready");
  await requestIdleAnimation();
  console.log("[Nanako] v11 Step 1.2 Python animation protocol renderer loaded.");
}

boot();
})();
